builders:
  converters:
    import: "package:firestore_obj/firestore_obj.dart"
    builder_factories: ["converters"]
    auto_apply: dependents
    build_extensions: { ".dart": [".converters.dart"] }
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
